apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniborrow-cash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniborrow-cash
  template:
    metadata:
      labels:
        app: uniborrow-cash
    spec:
      containers:
        - image:
            efodx/uniborrow-cash:2021-12-31-02-40-34
          name: uniborrow-cash
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://tyke.db.elephantsql.com/ystndsiu
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ystndsiu
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uniborrow-cash-db-pass
                  key: password
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://uniborrow-cash:8080
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: uniborrow-cluster
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: uniborrow-cash
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: uniborrow-cash
