kumuluzee:
  name: uniborrow-cash-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/cashDS
      connection-url: jdbc:postgresql://tyke.db.elephantsql.com/ystndsiu
      username: ystndsiu
      password: nH1g_ZvhEVo-nxMhq8SQa2XFH_10ZeWV
      pool:
        max-size: 1
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: 'http://localhost:2379'
  discovery:
    etcd:
      hosts: 'http://localhost:2379'
    metrics:
      web-instrumentation:
        - name: cash-endpoint
          url-pattern: /v1/cash/*
  openapi-mp:
    enabled: true
    servlet:
      mapping: /uniborrow-cash-openapi/
    ui:
      enabled: true
      mapping: /uniborrow-cash-openapi/ui
  dev:
    scan-libraries:
      - cash-models
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CashDB
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="8ff6c166-5030-437c-b97b-37178a04750d-ls.logit.io"
                                    port="24755" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
administration:
  maintenance-mode: false